installer:
  release: "v0.4.27"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:607f522d-325-9604"
  devtron:
    image: "quay.io/devtron/hyperion:c4e87419-280-9804"
    cicdImage: "quay.io/devtron/devtron:c4e87419-326-9806"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "c4e8741944379d11ac0b9c99acaffe4cfd7b0078"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "c4e8741944379d11ac0b9c99acaffe4cfd7b0078"
